In [1]:
egg_count = 0

def buy_eggs():
    egg_count += 12

buy_eggs()

In [ ]:
egg_count = 0

def buy_eggs(egg_count):
    egg_count += 12
    return egg_count

buy_eggs(egg_count)

In [ ]:
str1 = 'Function are important programming concepts'

def print_fn():
    str1 = "Variable scope is an important programming concepts"
    print (str1)

print_fn()
print (str1)

In [ ]:
def count_uppercase (string):
    num_upper = 0
    for char in string:
        if not char.isupper():
            continue
        num_upper += 1
    return num_upper

def count_uppercase_2 (string):
    num_upper = 0
    for char in string:
        if char.isupper():
            num_upper += 1
    return num_upper

def count_lowercase (string):
    num_upper = 0
    for char in string:
        if not char.islower():
            continue
        num_upper += 1
    return num_upper

In [ ]:
count_uppercase ("Introduction to Python")

In [ ]:
count_uppercase_2 ("Introduction to Python")

In [ ]:
count_lowercase ("Introduction to Python")

In [3]:
import numpy as np

In [ ]:
np.__version__

# Array

In [15]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print (arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
print (arr1[0])
print (arr1[3])
print (arr1[-1])

[1 2 3]
[10 11 12]
[10 11 12]


In [32]:
list1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
print (list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


In [33]:
print (list1[0][0])
print (list1[0,0])

1


TypeError: list indices must be integers or slices, not tuple

In [34]:
list1 [:]

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [22]:
list1 [0][0], list1[1][0], list1[2][0], list1[3][0]

(1, 4, 7, 10)

In [ ]:
print (arr1[0, 0])
print (arr1[0]) # ambil baris
print (arr1[:, 0]) # ambil kolom
print ('='*50)
print (arr1[:])

In [ ]:
arr1.dtype, type(arr1)

In [34]:
arr2 = np.array([[.1, .2], [.3, .4]])
print (arr2)
print (arr2.dtype)

[[0.1 0.2]
 [0.3 0.4]]
float64


In [ ]:
# bentuk Array
print ('Shape of Array 1:', arr1.shape)
print ('Shape of Array 2:', arr2.shape)

In [ ]:
# Dimensi Array
print ("Dimension of Array 1:", arr1.ndim)
print ("Dimension of Array 2:", arr2.ndim)

In [ ]:
arr3 = np.array([
    [
        [1, 2, 3],
        [11, 22, 33]
    ],
    [
        [4, 5, 6],
        [44, 55, 66]
    ],
    [
        [7, 8, 9],
        [77, 88, 99]
    ]
    
])
print (arr3)
print ('Shape of Array 3:', arr3.shape)
print ("Dimension of Array 3:", arr3.ndim)

## Array Otomatis

In [4]:
arr_zeros_1 = np.zeros(10) #array 1 dimensi yang panjangnya 10 semua nilai 0
arr_zeros_2 = np.zeros ((10, 5)) #list atau tuples
arr_zeros_3 = np.zeros ([5, 10, 10]) #list

print (arr_zeros_1, len(arr_zeros_1), arr_zeros_1.shape)
print ("*="*39)
print (arr_zeros_2, len(arr_zeros_2), arr_zeros_2.shape)
print ("*="*39)
print (arr_zeros_3, len(arr_zeros_3), arr_zeros_3.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 10 (10,)
*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 10 (10, 5)
*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.

In [5]:
arr_ones_1 = np.ones(10) #array 1 dimensi yang panjangnya 10 semua nilai 1
arr_ones_2 = np.ones ((10, 5)) #list atau tuples
arr_ones_3 = np.ones ([5, 10, 10]) #list

print (arr_ones_1, len(arr_ones_1), arr_ones_1.shape)
print ("*="*39)
print (arr_ones_2, len(arr_ones_2), arr_ones_2.shape)
print ("*="*39)
print (arr_ones_3, len(arr_ones_2), arr_ones_3.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 10 (10,)
*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 10 (10, 5)
*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1.

In [6]:
arr_empty_1 = np.empty((5, 5))
print (arr_empty_1)
print ("*="*39)
arr_empty_2 = np.empty((5, 1))
print (arr_empty_2)
print ("*="*39)
arr_empty_3 = np.empty((1000, 1000))
print (arr_empty_3)

[[6.23042070e-307 3.56043053e-307 1.60219306e-306 7.56571288e-307
  1.89146896e-307]
 [1.37961302e-306 1.05699242e-307 8.01097889e-307 1.78020169e-306
  7.56601165e-307]
 [1.02359984e-306 1.33510679e-306 2.22522597e-306 1.33511018e-306
  6.23057689e-307]
 [1.33511290e-306 1.78019082e-306 8.45559303e-307 8.06613040e-308
  6.89810244e-307]
 [1.22387550e-307 2.22522596e-306 8.34423917e-308 9.79107193e-307
  3.33509775e-317]]
*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=
[[7.56602523e-307]
 [1.29060531e-306]
 [2.04720783e-306]
 [1.11258277e-307]
 [1.33511562e-306]]
*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
np.arange(0, 10) #tanpa step

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0, 10, 2) #dengan step

array([0, 2, 4, 6, 8])

In [15]:
print (np.arange (0, 100, 2))
print (np.arange (10))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
[0 1 2 3 4 5 6 7 8 9]


## Array Append

In [27]:
arr_one = np.array([1, 2, 3, 4, 5])
arr_one

array([1, 2, 3, 4, 5])

In [28]:
np.append(arr_one, 10)

array([ 1,  2,  3,  4,  5, 10])

In [29]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 88,  9],
       [10, 11, 12]])

In [35]:
np.append (arr1, [13, 14, 15], axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [38]:
np.append (arr1, [[13, 14, 15]], axis = 0) #axis 0 untuk nambah baris

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [39]:
np.append (arr1, [[13, 14, 15]], axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 1

In [40]:
np.append (arr1, np.array([[13], [14], [15], [16]]), axis = 1) #axis 1 untuk nambah kolom

array([[ 1,  2,  3, 13],
       [ 4,  5,  6, 14],
       [ 7,  8,  9, 15],
       [10, 11, 12, 16]])

In [42]:
arr_ones_3

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]

In [49]:
np.append(arr_ones_3, np.zeros((1, 10, 10)), axis=0)
#np.append(arr_ones_3, np.zeros((1, 10, 10)), axis=0).shape

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]

In [52]:
arr_12 = np.arange(12)
print (arr_12)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [53]:
arr_12 = np.arange(12)
print (arr_12 + 1) #nambah 1 di masing2 elemen 

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [54]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
np.delete (arr1, 1, axis = 0) #menghapus dimensi 0 indeks ke 2

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
arr_unsorted = np.array ([3, 6, 1, 56, 10, 0])
print (arr_unsorted)
np.sort(arr_unsorted)

[ 3  6  1 56 10  0]


array([ 0,  1,  3,  6, 10, 56])

## Array Sort

In [88]:
arr3 = np.array([[11, 5, 7], [8, 12, 3], [4, 2, 6], [1, 9, 5]])
print (arr3)

[[11  5  7]
 [ 8 12  3]
 [ 4  2  6]
 [ 1  9  5]]


In [92]:
print (np.sort(arr3), "|", arr3. size, "|", arr3.shape)

[[ 5  7 11]
 [ 3  8 12]
 [ 2  4  6]
 [ 1  5  9]] | 12 | (4, 3)


In [103]:
print (np.sort(arr3, axis=0), arr3.ndim, arr3.shape)

[[ 1  2  3]
 [ 4  5  5]
 [ 8  9  6]
 [11 12  7]] 2 (4, 3)


In [104]:
arrexp = np.array(
[
    
    [[0, 1, 2, 3],
    [4, 5, 6, 7]],
    
    [[0, 1, 2, 3],
    [4, 5, 6, 7]],
    
    [[0, 1, 2, 3],
    [4, 5, 6, 7]],
])
print (arrexp, "|", arrexp.shape, "|", arrexp.size)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]] | (3, 2, 4) | 24


In [127]:
print(arr_unsorted)
arr_unsorted.shape

[ 3  6  1 56 10  0]


(6,)

In [108]:
vector_clm = np.array ([[1], [2], [3], [4], [5]])
print (vector_clm, "|", vector_clm.shape)

[[1]
 [2]
 [3]
 [4]
 [5]] | (5, 1)


In [111]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [110]:
np.reshape(arr1, (3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [116]:
np.reshape(arr1, (2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [114]:
np.reshape(arr1, (2,2,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [122]:
np.reshape(arr1, (3,1,4))

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [123]:
np.reshape(arr1, (4,1,3))

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]]])

In [124]:
np.reshape(arr1, (1,4,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [125]:
np.reshape(arr1, (1,3,4))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [4]:
arr_unsorted = np.array ([3, 6, 1, 56, 10, 0])
print (arr_unsorted)
arr_newaxis = arr_unsorted[np.newaxis]
print (arr_newaxis.shape)
print (arr_newaxis)

[ 3  6  1 56 10  0]
(1, 6)
[[ 3  6  1 56 10  0]]


In [13]:
arr_unsorted = np.array ([3, 6, 1, 56, 10, 0])
print (arr_unsorted)
vector_column = arr_unsorted[:, np.newaxis] #
print (vector_column.shape)
print (vector_column)
# arr_unsorted[:]

[ 3  6  1 56 10  0]
(6, 1)
[[ 3]
 [ 6]
 [ 1]
 [56]
 [10]
 [ 0]]


In [137]:
arr_unsorted = np.array ([3, 6, 1, 56, 10, 0])
print (arr_unsorted)
vector_row = arr_unsorted[np.newaxis, :]
print (vector_row.shape)
print (vector_row)

[ 3  6  1 56 10  0]
(1, 6)
[[ 3  6  1 56 10  0]]


In [20]:
arr1[:, :, np.newaxis].shape, arr1[..., np.newaxis].shape

((4, 3, 1), (4, 3, 1))

In [26]:
arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
arr1[arr1>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [28]:
arr1[arr1 % 2 == 0] #mencari isi dari array 1 yang bisa dibagi 2

array([ 2,  4,  6,  8, 10, 12])

In [30]:
arr1[(arr1>5) & (arr1<10)]

array([6, 7, 8, 9])

In [31]:
arr1[(arr1%2==0)&(arr1>5)]

array([ 6,  8, 10, 12])

In [32]:
arr1[(arr1%2==0)|(arr1%3==0)]

array([ 2,  3,  4,  6,  8,  9, 10, 12])

In [48]:
arr_stack_1 = np.array ((1, 2, 3))
arr_stack_2 = np.array ((2, 3, 4))
arr_stack_3 = np.array ((3, 4, 5))
np.stack((arr_stack_1, arr_stack_2, arr_stack_3)) #jika stack tanpa v atau h, maka otomatis stack akan menjadi vertical stack

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [49]:
np.vstack((arr_stack_1, arr_stack_2, arr_stack_3))

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [51]:
np.hstack((arr_stack_1, arr_stack_2, arr_stack_3))

array([1, 2, 3, 2, 3, 4, 3, 4, 5])

In [53]:
arr_split = np.arange(16).reshape(4,4)
arr_split

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
np.hsplit(arr_split, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [64]:
np.vsplit(arr_split, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [55]:
np.hsplit(arr_split, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [65]:
np.vsplit(arr_split, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [61]:
np.hsplit(arr_split, np.array([3, 6]))

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([], shape=(4, 0), dtype=int32)]

In [68]:
arr4 = arr1*4
print (arr1)
print (arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 4  8 12]
 [16 20 24]
 [28 32 36]
 [40 44 48]]


In [74]:
np.concatenate ((arr1, arr4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36],
       [40, 44, 48]])

In [75]:
print (np.concatenate ((arr1, arr4)))
print (np.concatenate ((arr1, arr4), axis = 1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 4  8 12]
 [16 20 24]
 [28 32 36]
 [40 44 48]]
[[ 1  2  3  4  8 12]
 [ 4  5  6 16 20 24]
 [ 7  8  9 28 32 36]
 [10 11 12 40 44 48]]


In [92]:
arr4[:]

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36],
       [40, 44, 48]])

In [89]:
arr4.sum(), np.sum(arr4)

(312, 312)

In [88]:
sum (arr4) #Native Python

array([ 88, 104, 120])

In [91]:
print (arr4.sum(axis=0))

[ 88 104 120]


In [93]:
print (arr4.sum(axis=1))

[ 24  60  96 132]


In [95]:
print(arr4.std(), "|", arr4.mean(), "|", arr4.max(), "|", arr4.min())

13.808210118138652 | 26.0 | 48 | 4


In [111]:
print(arr1)
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 4  8 12]
 [16 20 24]
 [28 32 36]
 [40 44 48]]


In [96]:
arr1.shape, arr4.shape

((4, 3), (4, 3))

In [104]:
print(arr1+arr4) #penjumlahan
# arr1.dot(arr4.transpose())
print(arr1.dot(arr4.transpose()))

[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]]
[[  56  128  200  272]
 [ 128  308  488  668]
 [ 200  488  776 1064]
 [ 272  668 1064 1460]]


In [105]:
print (arr1.dot(arr4.T))

[[  56  128  200  272]
 [ 128  308  488  668]
 [ 200  488  776 1064]
 [ 272  668 1064 1460]]


In [107]:
print (np.multiply(arr1, arr4))

[[  4  16  36]
 [ 64 100 144]
 [196 256 324]
 [400 484 576]]


In [109]:
print(arr1 * arr4)

[[  4  16  36]
 [ 64 100 144]
 [196 256 324]
 [400 484 576]]


In [113]:
np.matmul(arr1, arr4.T)

array([[  56,  128,  200,  272],
       [ 128,  308,  488,  668],
       [ 200,  488,  776, 1064],
       [ 272,  668, 1064, 1460]])

In [126]:
arr5 = np.array([3, 6, 9])
print(arr5)
arr6 = np.array([9, 3, 6])
print(arr6)
np.matmul(arr5,arr6)

[3 6 9]
[9 3 6]


99