# Tugas

1. Create a 2-D numpy array o shape (20, 1) in interval [0, 1] (1 is exclusive.
2. Reshape that array into shape of (10, 2)
3. Then create a new 2D array with the same shape and 2 times of the previous array
4. Perform matric multiplication between those array such that the result will have a shape o (10, 10)
5. Get the statistic summary (mean, median, variance, and standard deviation) from the resulted array for each columns.

## Import Numpy

In [2]:
import numpy as np

## 1

In [3]:
arr_tugas = np.arange(0, 1, 5e-2)[:, None]
print (arr_tugas, arr_tugas.shape)

[[0.  ]
 [0.05]
 [0.1 ]
 [0.15]
 [0.2 ]
 [0.25]
 [0.3 ]
 [0.35]
 [0.4 ]
 [0.45]
 [0.5 ]
 [0.55]
 [0.6 ]
 [0.65]
 [0.7 ]
 [0.75]
 [0.8 ]
 [0.85]
 [0.9 ]
 [0.95]] (20, 1)


## 2 

In [5]:
arr_tugas = arr_tugas.reshape(10,2)
print(arr_tugas, arr_tugas.shape)

[[0.   0.05]
 [0.1  0.15]
 [0.2  0.25]
 [0.3  0.35]
 [0.4  0.45]
 [0.5  0.55]
 [0.6  0.65]
 [0.7  0.75]
 [0.8  0.85]
 [0.9  0.95]] (10, 2)


## 3

In [6]:
# arr_tugas2 = arr_tugas*2
arr_tugas2 = arr_tugas.dot(2)
print (arr_tugas2, arr_tugas2.shape)

[[0.  0.1]
 [0.2 0.3]
 [0.4 0.5]
 [0.6 0.7]
 [0.8 0.9]
 [1.  1.1]
 [1.2 1.3]
 [1.4 1.5]
 [1.6 1.7]
 [1.8 1.9]] (10, 2)


## 4

In [7]:
arr_tugas3 = np.matmul (arr_tugas, arr_tugas2.T)
print (arr_tugas3, arr_tugas3.shape)

[[0.005 0.015 0.025 0.035 0.045 0.055 0.065 0.075 0.085 0.095]
 [0.015 0.065 0.115 0.165 0.215 0.265 0.315 0.365 0.415 0.465]
 [0.025 0.115 0.205 0.295 0.385 0.475 0.565 0.655 0.745 0.835]
 [0.035 0.165 0.295 0.425 0.555 0.685 0.815 0.945 1.075 1.205]
 [0.045 0.215 0.385 0.555 0.725 0.895 1.065 1.235 1.405 1.575]
 [0.055 0.265 0.475 0.685 0.895 1.105 1.315 1.525 1.735 1.945]
 [0.065 0.315 0.565 0.815 1.065 1.315 1.565 1.815 2.065 2.315]
 [0.075 0.365 0.655 0.945 1.235 1.525 1.815 2.105 2.395 2.685]
 [0.085 0.415 0.745 1.075 1.405 1.735 2.065 2.395 2.725 3.055]
 [0.095 0.465 0.835 1.205 1.575 1.945 2.315 2.685 3.055 3.425]] (10, 10)


## 5

In [31]:
arr_tugas_mean = arr_tugas3.mean(axis=0)
print (arr_tugas_mean)

[0.05 0.24 0.43 0.62 0.81 1.   1.19 1.38 1.57 1.76]


In [32]:
arr_tugas_median = np.median (arr_tugas3, axis=0)
print (arr_tugas_median)

[0.05 0.24 0.43 0.62 0.81 1.   1.19 1.38 1.57 1.76]


In [33]:
arr_tugas_std = arr_tugas3.std(axis=0)
print (arr_tugas_std)

[0.02872281 0.14361407 0.25850532 0.37339657 0.48828782 0.60317908
 0.71807033 0.83296158 0.94785284 1.06274409]


In [34]:
print (arr_tugas3.std(axis=0))

[0.02872281 0.14361407 0.25850532 0.37339657 0.48828782 0.60317908
 0.71807033 0.83296158 0.94785284 1.06274409]


In [36]:
arr_tugas_var = np.var(arr_tugas3, axis=0)
print (arr_tugas_var)

[8.250000e-04 2.062500e-02 6.682500e-02 1.394250e-01 2.384250e-01
 3.638250e-01 5.156250e-01 6.938250e-01 8.984250e-01 1.129425e+00]


In [37]:
print (arr_tugas3.var(axis=0))

[8.250000e-04 2.062500e-02 6.682500e-02 1.394250e-01 2.384250e-01
 3.638250e-01 5.156250e-01 6.938250e-01 8.984250e-01 1.129425e+00]
